$TASK_NEXT_TRY = 0;
$TASK_NDEPS = 1;
$TASK_INO = 2;
$TASK_JOB = 3;
$TASK_WAITERS = 4;
$TASK_NDEPS = 5;
$TASK_DEFUNCT = 6;
$TASK_BIRTH = 7;
$TASK_NEEDS_DONE = 8;

$JOB_INO = 0;
$JOB_NTASKS = 1;
$JOB_FAILED = 2;
$JOB_NDEPS = 3;

$TASK_SUCCESS_CODE = 0;
$TASK_DEFERRAL_CODE = 99;
$TASK_FAILURE_CODE = 100;

sub SLEEPYTIME() { 60 }

1;
