#!/usr/bin/perl

# mcfeely        Asynchronous remote task execution.
# Copyright (C) 1999 Kiva Networking
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# You may contact the author at <mml@pobox.com>.

use McFeely::Internal;
use strict;
use Fcntl;

require 'chdir.pl';
require 'log.pl';

&chdir_top or &bail("Could not chdir: $!");

pipe SIR, SIW;
pipe SRR, SRW;
fcntl(SRR, F_SETFL, fcntl(SRR, F_GETFL, 0)|O_NONBLOCK);

my $pid = fork;
if (!defined $pid) {
    die "cannot fork: $!\n";
} elsif ($pid == 0) {
    close SIW; close SRR;
    open STDIN, '<&SIR';
    open STDOUT, '>&SRW';
    exec 'bin/mcfeely-spawn';
}

close SIR; close SRW;
exec 'bin/mcfeely-manage', fileno SRR, fileno SIW;
