#!/usr/bin/perl
# vi:ts=4:sw=4:sm:ai:et:

use vars qw( $Asked_to_exit $Tasks_in_progress @Tasks %Task %Job );

require 'log.pl';
require 'safe_to_exit.pl';
require 'files.pl';
require 'tasks.pl';
require 'jobs.pl';
require 'attempt_tasks.pl';
require 'do_select.pl';
require 'read_results.pl';

chdir '/home/mliggett/mcfeely-test' or bail("Could not chdir: $!; exiting.");
chdir 'queue' or bail("Could not chdir: $!; exiting.");

scan_job('job', 0);

until ($Asked_to_exit && safe_to_exit) {
    scan_job('newj', 1);
    attempt_tasks();
    do_select();
    read_results();
}
